#################
# ALIASES
#################
alias ll="ls -lhA"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

#################
# EXPORTS
#################
export PYTHONPATH="/usr/local/bin/python3:$PYTHONPATH"
export WORKON_HOME=$HOME/.virtualenvs
export EDITOR="code"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
#export PROJECT_HOME=$HOME/Devel
#export PATH=$PATH

#################
# SERVERLESS
#################
# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash ] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash