" Vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin()
Plug 'sainnhe/edge'
Plug 'vim-scripts/auto-pairs-gentle'
Plug 'vim-airline/vim-airline'
Plug 'sheerun/vim-polyglot'
Plug 'preservim/nerdtree'
Plug 'airblade/vim-gitgutter'
Plug 'ekalinin/dockerfile.vim'
Plug 'chr4/nginx.vim'
Plug 'fatih/vim-go'
Plug 'rust-lang/rust.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'tpope/vim-fugitive'
Plug 'vim-scripts/c.vim'
call plug#end()

" Plugin options
let g:rustfmt_autosave = 1
" ctrl+n to open NERDTree
map <C-n> :NERDTreeToggle<CR>

"Syntax highlighting
syntax on

" colorscheme setup
set termguicolors
set background=dark
let g:edge_style = 'neon'
let g:edge_disable_italic_comment = 1
let g:airline_theme= 'edge'
colorscheme edge

" Indentation
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set textwidth=80

" Mouse and Display
set mouse=a
set ttyfast
set showcmd
set showmode
set number

" Search
set showmatch
set smartcase
set hlsearch
set incsearch
