" Vim-plug
call plug#begin()
Plug 'sainnhe/edge'
Plug 'vim-scripts/auto-pairs-gentle'
Plug 'vim-airline/vim-airline'
call plug#end()

"Syntax highlighting
syntax on

" colorscheme setup
set termguicolors
set background=dark
let g:edge_style = 'neon'
let g:edge_disable_italic_comment = 1
let g:airline_theme= 'edge'
colorscheme edge

" Indentation
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set textwidth=80

" Mouse and Display
set mouse=a
set ttyfast
set showcmd
set showmode
set number

" Search
set showmatch
set smartcase
set hlsearch
set incsearch
